export interface Coordinates {
    lat: number;
    lng: number;
}

export interface AreaOption {
    id: string
    name: string // e.g., "North London (Angel)"
    description: string
    center: { lat: number, lng: number }
    travel_times: Record<string, { to: number; home: number }> // member_id -> { to: mins, home: mins }
}

export interface Round {
    id: string
    code: string // 6-digit
    host_id: string
    created_at: string
    status: 'active' | 'completed' | 'expired'
    stage: 'lobby' | 'voting' | 'pub_voting' | 'results' // New
    area_options?: AreaOption[] // New
    settings: {
        mode: 'optimized' | 'capped'
        max_travel_time?: number // minutes
    }
}

export interface PartyMember {
    id: string
    round_id: string
    name: string
    photo_path?: string // from Supabase Storage
    transport_mode: 'walking' | 'cycling' | 'transit'
    status: 'pending' | 'ready' // ready = location set
    location?: {
        lat: number
        lng: number
        address?: string
    }
    // Location Preference Fields
    start_location_type?: 'live' | 'station'
    start_station_id?: string
    end_location_type?: 'same' | 'station'
    end_station_id?: string

    vote_area_id?: string // New
    joined_at: string
}

export interface PubRecommendation {
    place_id: string
    name: string
    rating: number
    vicinity: string // address
    photos?: string[]
    vibe_summary: string // Generated by Gemini
    travel_times: Record<string, { to: number; home: number }> // member_id -> { to: mins, home: mins }
    total_travel_time: number
    fairness_score: number
}
