export interface Coordinates {
    lat: number;
    lng: number;
}

export interface AreaOption {
    id: string
    name: string // e.g., "North London (Angel)"
    description: string
    center: { lat: number, lng: number }
    travel_times: Record<string, {
        to: number;
        home: number;
        summary_to?: string;
        summary_home?: string;
        start_name?: string;
        end_name?: string;
    }> // member_id -> details
    ai_rationale?: string
    scoring?: {
        avg_time: number
        max_time: number
        outlier_name?: string
        penalty: number
        total_time: number
    }
}

export interface Round {
    id: string
    code: string // 6-digit
    host_id: string
    created_at: string
    status: 'active' | 'completed' | 'expired'
    stage: 'lobby' | 'voting' | 'pub_voting' | 'results' // New
    area_options?: AreaOption[] // New
    settings: {
        mode: 'optimized' | 'capped'
        max_travel_time?: number // minutes
        ai_strategy?: string // New: Global Narrative
        winning_pub_id?: string
        system_message?: string
        meeting_time?: string
    }
}

export interface PartyMember {
    id: string
    round_id: string
    name: string
    photo_path?: string // from Supabase Storage
    transport_mode: 'train_only' | 'bus_only' | 'no_preference'
    status: 'pending' | 'ready' // ready = location set
    location?: {
        lat: number
        lng: number
        address?: string
    }
    // Location Preference Fields
    start_location_type?: 'live' | 'station' | 'custom'
    start_station_id?: string
    end_location_type?: 'same' | 'station' | 'custom'
    end_station_id?: string

    vote_area_id?: string // New
    vote_pub_id?: string // New
    joined_at: string
    end_lat?: number
    end_lng?: number
    user_id?: string // Supabase Auth User ID (Host/Claimed)
}

export interface PubRecommendation {
    place_id: string
    name: string
    rating: number
    vicinity: string // address
    photos?: string[]
    vibe_summary: string // Generated by Gemini
    travel_times: Record<string, {
        to: number;
        home: number;
        summary_to?: string;
        summary_home?: string;
        start_name?: string;
        end_name?: string;
    }>
    total_travel_time: number
    fairness_score: number
    location?: {
        lat: number
        lng: number
    }
}
